import type { Metadata } from "next"
import "./globals.css"
import { Baskervville, Montserrat } from "next/font/google"
import { Header } from "./components/header"
import { Footer } from "./components/footer"
import { ButtonsSocialNetworks } from "./components/ButtonsSocialNetworks"

export const metadata: Metadata = {
  title: " Create Next App",
  description: "Generated by create next app",
}

const baskervville = Baskervville({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-baskervville",
})

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-montserrat",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={` ${montserrat.className} `}>
        <>
          <Header />
          {children}
        </>
      </body>
    </html>
  )
}
