import type { Metadata } from "next"
import "./globals.css"
import { Baskervville, Montserrat } from "next/font/google"
import { Header } from "./components/header"
import { StoreInitializer } from "./stores/store.initializer"
import { FetchServices } from "./components/fetch-services"

export const metadata: Metadata = {
  title: " Create Next App",
  description: "Generated by create next app",
}

const baskervville = Baskervville({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-baskervville",
})

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-montserrat",
})

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const { services } = await FetchServices()
  return (
    <html lang="en">
      <body className={` ${montserrat.className} `}>
        <StoreInitializer allServices={services} />
        <Header />
        {children}
      </body>
    </html>
  )
}
