import type { Metadata } from "next"
import "./globals.css"
import { Baskervville, Montserrat } from "next/font/google"

export const metadata: Metadata = {
  title: " Create Next App",
  description: "Generated by create next app",
}

const baskervville = Baskervville({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-baskervville",
})

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-montserrat",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${baskervville.variable} ${montserrat.variable} font-sans`}
      >
        {children}
      </body>
    </html>
  )
}
